spring:
  application:
    name: invoice-service

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${INVOICE_DB_NAME};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8083

services:
  customer:
    url: ${CUSTOMER_SERVICE_URL}

  catalog:
    url: ${CATALOG_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics